# Generated by Django 5.2.13 on 2026-04-15 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('url', models.URLField(max_length=500, verbose_name='链接地址')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='描述')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标标识')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='主题色')),
                ('category', models.CharField(choices=[('project', '项目展示'), ('server', '服务器管理'), ('tool', '工具'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='是否可见')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '服务链接',
                'verbose_name_plural': '服务链接',
                'db_table': 'homepage_service_link',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
