# Generated by Django 5.2.13 on 2026-05-18 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_repair_legacy_user_foreign_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="QWeb", max_length=100, verbose_name="站点名称"
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Qintsg's Web",
                        max_length=150,
                        verbose_name="浏览器标题",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="把服务入口、身份权限、审计记录和个人项目收束到一个可控门户。",
                        max_length=300,
                        verbose_name="站点副标题",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="Logo 地址"
                    ),
                ),
                (
                    "favicon_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="favicon 地址",
                    ),
                ),
                (
                    "brand_initial",
                    models.CharField(
                        blank=True, default="Q", max_length=4, verbose_name="品牌首字母"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点元数据",
                "verbose_name_plural": "站点元数据",
                "db_table": "homepage_site_metadata",
                "ordering": ["-updated_at"],
            },
        ),
    ]
