#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
定义 audit 应用的数据库迁移。
@Project : QWeb
@File : 0001_initial.py
@Author : Qintsg
@Date : 2026-05-12 00:00
'''
# Generated by Django 5.2.13 on 2026-05-12 03:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """记录当前应用的数据库迁移步骤。"""
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("assign", "分配"),
                            ("revoke", "撤销"),
                            ("approve", "审批"),
                            ("reject", "拒绝"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        help_text="如 accounts、iam、blog 等",
                        max_length=50,
                        verbose_name="模块",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="如 user、role、permission 等",
                        max_length=100,
                        verbose_name="操作资源",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="资源 ID"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="变更前后、参数等 JSON 信息",
                        verbose_name="操作详情",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作审计日志",
                "verbose_name_plural": "操作审计日志",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="登录失败时 user 可能为 null，此字段保留尝试的用户名",
                        max_length=32,
                        verbose_name="登录用户名",
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        db_index=True,
                        default="password",
                        max_length=32,
                        verbose_name="登录方式",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="第三方平台"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录成功"),
                            ("logout", "登出"),
                            ("failed", "登录失败"),
                            ("oauth_bind", "OAuth 绑定"),
                            ("oauth_register", "OAuth 自动注册"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "device_info",
                    models.JSONField(blank=True, default=dict, verbose_name="设备信息"),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否登录成功"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, null=True, verbose_name="失败原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "db_table": "user_login_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
