#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
定义 accounts 应用的数据库迁移。
@Project : QWeb
@File : 0001_initial.py
@Author : Qintsg
@Date : 2026-05-12 00:00
'''
# Generated by Django 5.2.13 on 2026-05-12 03:01

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """记录当前应用的数据库迁移步骤。"""
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uid",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="用户 UID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="3-32 个字符，允许字母、数字、短横线、下划线和点号。",
                        max_length=32,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="展示昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.TextField(blank=True, null=True, verbose_name="头像 URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("inactive", "未激活"),
                            ("banned", "已封禁"),
                            ("deleted", "已删除"),
                            ("pending", "待确认"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                        verbose_name="账号状态",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("normal", "普通用户"),
                            ("admin", "管理员"),
                            ("system", "系统用户"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=32,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="与 status 一起用于 Django 认证框架判断。",
                        verbose_name="Django 认证是否启用",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="允许访问 Django Admin 后台。",
                        verbose_name="管理后台权限",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="软删除时间"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="真实姓名"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男"),
                            ("female", "女"),
                            ("other", "其他"),
                            ("unknown", "未知"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="个人简介"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "website",
                    models.TextField(blank=True, null=True, verbose_name="个人网站"),
                ),
                (
                    "github",
                    models.TextField(blank=True, null=True, verbose_name="GitHub 主页"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展资料"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserSecurity",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="security",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "password_hash",
                    models.TextField(
                        blank=True, null=True, verbose_name="密码哈希快照"
                    ),
                ),
                (
                    "password_algo",
                    models.CharField(
                        blank=True,
                        default="django",
                        max_length=32,
                        null=True,
                        verbose_name="密码算法",
                    ),
                ),
                (
                    "password_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="密码更新时间"
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(default=False, verbose_name="是否开启二次验证"),
                ),
                (
                    "two_factor_secret_enc",
                    models.TextField(
                        blank=True, null=True, verbose_name="加密后的 2FA 密钥"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(default=0, verbose_name="连续登录失败次数"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="账号锁定到期时间"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="最后登录 IP"
                    ),
                ),
                (
                    "last_login_user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="最后登录设备 UA"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户安全信息",
                "verbose_name_plural": "用户安全信息",
                "db_table": "user_security",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh-CN", max_length=32, verbose_name="语言偏好"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai", max_length=64, verbose_name="时区"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "浅色"),
                            ("dark", "深色"),
                            ("system", "跟随系统"),
                        ],
                        default="system",
                        max_length=32,
                        verbose_name="主题",
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="通知设置"),
                ),
                (
                    "privacy_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="隐私设置"),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="其他偏好设置"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户设置",
                "verbose_name_plural": "用户设置",
                "db_table": "user_settings",
            },
        ),
        migrations.CreateModel(
            name="UserOAuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="绑定记录 ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")],
                        db_index=True,
                        max_length=64,
                        verbose_name="第三方平台",
                    ),
                ),
                (
                    "provider_account_id",
                    models.CharField(max_length=255, verbose_name="第三方平台用户 ID"),
                ),
                (
                    "provider_username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="第三方平台用户名",
                    ),
                ),
                (
                    "provider_nickname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="第三方平台显示名称",
                    ),
                ),
                (
                    "provider_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="第三方平台邮箱",
                    ),
                ),
                (
                    "provider_email_verified",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="第三方平台邮箱是否已验证"
                    ),
                ),
                (
                    "provider_avatar_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="第三方平台头像"
                    ),
                ),
                (
                    "access_token_enc",
                    models.TextField(
                        blank=True, null=True, verbose_name="加密后的访问令牌"
                    ),
                ),
                (
                    "refresh_token_enc",
                    models.TextField(
                        blank=True, null=True, verbose_name="加密后的刷新令牌"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="令牌过期时间"
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(blank=True, null=True, verbose_name="授权范围"),
                ),
                (
                    "raw_profile",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="第三方原始用户信息"
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="本地用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "第三方账号绑定",
                "verbose_name_plural": "第三方账号绑定",
                "db_table": "user_oauth_accounts",
            },
        ),
        migrations.CreateModel(
            name="UserRefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="令牌记录 ID"
                    ),
                ),
                (
                    "token_hash",
                    models.TextField(unique=True, verbose_name="刷新令牌哈希"),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="设备 ID"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="设备名称"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="签发 IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="客户端 UA"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="吊销时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户刷新令牌",
                "verbose_name_plural": "用户刷新令牌",
                "db_table": "user_refresh_tokens",
            },
        ),
        migrations.CreateModel(
            name="UserContact",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="contact",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="邮箱验证时间"
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="手机号验证时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户联系方式",
                "verbose_name_plural": "用户联系方式",
                "db_table": "user_contact",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("email__isnull", False)),
                        name="uq_user_contact_email_ci",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="uq_users_username_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="useroauthaccount",
            index=models.Index(
                fields=["provider", "provider_username"],
                name="user_oauth__provide_93194a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useroauthaccount",
            index=models.Index(
                fields=["provider", "provider_email"],
                name="user_oauth__provide_fba701_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="useroauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_account_id"),
                name="uq_oauth_provider_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="useroauthaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="uq_oauth_user_provider"
            ),
        ),
        migrations.AddIndex(
            model_name="userrefreshtoken",
            index=models.Index(
                fields=["user", "created_at"], name="user_refres_uid_c30775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrefreshtoken",
            index=models.Index(
                fields=["revoked_at"], name="user_refres_revoked_5a930e_idx"
            ),
        ),
    ]
