# Generated by Django 6.0.3 on 2026-03-30 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='用户 ID')),
                ('username', models.CharField(db_index=True, help_text='3-64 个字符，仅限字母、数字、下划线。', max_length=64, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, help_text='未激活的用户无法登录。', verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, help_text='允许访问 Django Admin 后台。', verbose_name='管理后台权限')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('avatar', models.URLField(blank=True, default='', help_text='头像图片 URL。', verbose_name='头像')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='个人简介')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('language', models.CharField(default='zh-hans', help_text='IETF 语言标签，如 zh-hans、en-us。', max_length=10, verbose_name='首选语言')),
                ('theme_preference', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '跟随系统')], default='auto', max_length=10, verbose_name='主题偏好')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'accounts_user_profile',
            },
        ),
    ]
