# Generated by Django 5.2.13 on 2026-05-11 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")],
                        db_index=True,
                        max_length=32,
                        verbose_name="OAuth 提供方",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(max_length=128, verbose_name="提供方用户 ID"),
                ),
                (
                    "provider_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="提供方用户名",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="提供方邮箱",
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, default="", verbose_name="头像 URL"),
                ),
                (
                    "profile_url",
                    models.URLField(blank=True, default="", verbose_name="资料页 URL"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近登录时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="本地用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth 身份绑定",
                "verbose_name_plural": "OAuth 身份绑定",
                "db_table": "accounts_oauth_identity",
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_username"],
                        name="accounts_oa_provide_c00bb5_idx",
                    ),
                    models.Index(
                        fields=["provider", "email"],
                        name="accounts_oa_provide_90b448_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="uniq_oauth_provider_user",
                    ),
                    models.UniqueConstraint(
                        fields=("provider", "user"),
                        name="uniq_oauth_provider_local_user",
                    ),
                ],
            },
        ),
    ]
